print('Input')
nama = input('Nama                 : ')
nim = input('NIM                  : ')
paralel = input('Kelas Paralel        : ')
ttl = input('Tempat/Tanggal Lahir : ')
alamat = input('Alamat               : ')
hobi = input('Hobby                : ')
hp = input('No. Hp               : ')

print('\nOutput')
print('Nama                 : ', nama)
print('NIM                  : ', nim)
print('Kelas Paralel        : ', paralel)
print('Tempat/Tanggal Lahir : ', ttl)
print('Alamat               : ', alamat)
print('Hobby                : ', hobi)
print('No. Hp               : ', hp)